### ISSUE TITLE
Cannot read property 'prototype' of undefined?

### ISSUE THREAD

**Issue by leafiy** [john-doherty/swiped-events#1]
![image](https://user-images.githubusercontent.com/870449/38798697-d60decd8-4194-11e8-9629-2504c012f915.png)

**Comment by john-doherty** [comment]
Hi @leafiy, can you include some code that allows this to be reproduced?

**Comment by endel** [comment]
This happens when trying to use this package as a node module with webpack. 

Ideally, the `"main"` on `package.json` should be the actual pure-swipe implementation, bundled using UMD, like this: https://github.com/umdjs/umd/blob/master/templates/jqueryPlugin.js

**Comment by endel** [comment]
I've made a fix for this on #2

**Comment by endel** [comment]
Thanks a lot for merging @john-doherty, I think you forgot to publish the latest version on npm though :)

Cheers!

**Comment by john-doherty** [comment]
Good point. Done :)
