### ISSUE TITLE
npm install deprecation warnings

### ISSUE THREAD

**Issue by ram-you** [john-doherty/swiped-events#20]
Hi, on npm i swiped-events, have the following warning:
**npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.**

**Comment by JaZo** [comment]
It looks like the dependency is accidentially installed as regular dependency instead of dev dependency as I can't see it being used in the code. Maybe it can even be removed completely?
