### ISSUE TITLE
console.log statement pollutes developer console

### ISSUE THREAD

**Issue by saeedahmadee** [john-doherty/swiped-events#4]
I am using this script on a production level website, I don't think logging every swipe is needed all the time.
This line just does that:

if (console && console.log) console.log(eventType + ' fired on ' + startEl.tagName);

Also, I am open if there is any chance of contributing.

**Comment by john-doherty** [comment]
Hi, you should be using the minified files in the dist folder in
production. The build script that produces them removes console logs

**Comment by saeedahmadee** [comment]
I am just importing the JS file with require function, and it logs every swipe.

**Comment by john-doherty** [comment]
Ok all sorted. Thanks for raising this
