### ISSUE TITLE
Better feature detection for CustomEvent

### ISSUE THREAD

**Issue by TimVevida** [john-doherty/swiped-events#5]
The if-statement that detects if the CustomEvent constructor is supported is too broad and gets executed in modern browsers. Loads of browsers ([link to MDN](https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/CustomEvent)) still support the (deprecated) initCustomEvent function.

Solution: replace
```
if ('initCustomEvent' in document.createEvent('CustomEvent')) {
```

with
```
if (typeof window.CustomEvent !== "function" ) {
```

**Comment by john-doherty** [comment]
@TimVevida is this causing an issue? I'm super busy right now but happy to accept a pull request if you have the time

**Comment by john-doherty** [comment]
Thank you!
